"""
Savings Verification & Measurement & Verification (M&V) Engine
Implements:
1. Complete Savings Lifecycle:
   BASELINE -> PREDICTED -> APPROVED -> SIMULATED ACTUAL -> VERIFIED
2. Predicted vs Actual Comparison Matrix:
   BEFORE | PREDICTED | ACTUAL across Energy, SEC, Cost, CO2, Production, Quality
3. Auditable IPMVP Option B (Sub-meter Isolation) Verification Protocol
4. Production-Safe Savings Qualification:
   Only certified as "VERIFIED PRODUCTION-SAFE SAVING" when all physical constraints,
   quality tolerances, and machine limits pass in the post-action state.

DISCLAIMER:
All post-action values in this demo are SIMULATED DEMO DATA generated by the
deterministic factory simulation model. Never presented as unverified field claims.
"""

from typing import List, Dict, Any, Optional
from .models import (
    VerifiedSavingsRecord, 
    PredictedVsActualVerification, 
    MetricComparisonRow
)
from .simulation import factory_simulator, GRID_CO2_FACTOR_KG_PER_KWH

# Core industrial parameters for Shakti Foundry (Peenya, Bengaluru)
ELECTRICITY_TARIFF_INR_PER_KWH = 8.20
NOMINAL_DAILY_PRODUCTION_TONS = 24.5

def get_verified_savings_history() -> List[VerifiedSavingsRecord]:
    """
    Returns auditable, measurement-and-verification (M&V) records.
    Explicitly distinguishes between Predicted savings and Actual Verified savings,
    explaining variance due to production mix, weather, or operating hours.
    Follows IPMVP (International Performance Measurement and Verification Protocol).
    """
    records = []

    # Dynamically verified live actions (added if applied in current session)
    if "action_compressor_unloaded_shutdown" in factory_simulator.applied_actions:
        records.append(VerifiedSavingsRecord(
            id="vrf_c2_auto_shutdown",
            action_title="90-sec Auto-Idle Shutdown & Tighten Pressure Band to 6.6 bar",
            machine_name="Compressor 02 (Kaeser Screw 75kW)",
            implemented_date="Live Verification (Simulated Post-Action Telemetry)",
            predicted_sec_improvement_pct=6.4,
            actual_sec_improvement_pct=5.8,
            kwh_saved_monthly=3156.0,
            inr_saved_monthly=25879.0,
            co2_avoided_kg_monthly=2260.0,
            production_impact_pct=0.0,
            quality_impact_pct=0.0,
            variance_explanation="Actual improvement is 5.8% vs predicted 6.4% due to unexpected short-batch sand preparation runs requiring occasional extra pneumatic actuation.",
            verification_methodology="IPMVP Option B (Isolated Sub-meter + Pneumatic Pressure Continuous Verification)"
        ))

    if "action_furnace_refractory_patch" in factory_simulator.applied_actions:
        records.append(VerifiedSavingsRecord(
            id="vrf_f2_refractory",
            action_title="Scheduled Refractory Dry-Vibe Patch & Fast-Cycle Slag Skim SOP",
            machine_name="Furnace 02 (Holding Furnace 450kW)",
            implemented_date="Live Verification (Simulated Post-Action Telemetry)",
            predicted_sec_improvement_pct=15.6,
            actual_sec_improvement_pct=14.9,
            kwh_saved_monthly=7680.0,
            inr_saved_monthly=62976.0,
            co2_avoided_kg_monthly=5499.0,
            production_impact_pct=0.0,
            quality_impact_pct=0.0,
            variance_explanation="Actual improvement is 14.9% vs predicted 15.6% due to high proportion of heavy rust on incoming scrap pile in first heat.",
            verification_methodology="IPMVP Option B (Melt Energy Sub-meter + Weighbridge Net Melted Ton Normalization)"
        ))

    if "action_tod_rescheduling" in factory_simulator.applied_actions:
        records.append(VerifiedSavingsRecord(
            id="vrf_tod_sched",
            action_title="Shift Primary Heat Pre-Melting to Night Off-Peak Slot",
            machine_name="Melting & Holding System",
            implemented_date="Live Verification (TOD Tariff Re-alignment)",
            predicted_sec_improvement_pct=0.0,
            actual_sec_improvement_pct=0.0,
            kwh_saved_monthly=0.0,
            inr_saved_monthly=126000.0,
            co2_avoided_kg_monthly=0.0,
            production_impact_pct=0.0,
            quality_impact_pct=0.0,
            variance_explanation="Tariff cost reduction verified against BESCOM 15-minute TOD utility smart meter billing log.",
            verification_methodology="IPMVP Option C (Utility Revenue Billing Meter Interval Analysis)"
        ))

    # Historical verified record 1: Pump 01 VFD Modulation (Implemented 45 days ago)
    records.append(VerifiedSavingsRecord(
        id="vrf_pump01_vfd",
        action_title="Pump 01 Cooling Loop VFD Retrofit & Temperature-Controlled Modulation",
        machine_name="Pump 01 (Cooling Circulation 45kW)",
        implemented_date="45 days ago (Verified over 30-day baseline)",
        predicted_sec_improvement_pct=18.5,
        actual_sec_improvement_pct=16.8,
        kwh_saved_monthly=4620.0,
        inr_saved_monthly=37884.0,
        co2_avoided_kg_monthly=3308.0,
        production_impact_pct=0.0,
        quality_impact_pct=0.0,
        variance_explanation="Variance of -1.7% due to higher summer ambient temperatures in Bengaluru (+3.2°C above baseline period), which increased cooling tower fan hours.",
        verification_methodology="IPMVP Option B (Dedicated Sub-meter Isolation & Temperature Normalization)"
    ))

    # Historical verified record 2: Finishing Line Dust Collector Timer Automation (Implemented 75 days ago)
    records.append(VerifiedSavingsRecord(
        id="vrf_finishing_timer",
        action_title="Finishing Line Dust Collector Delta-P Auto-Purge Optimization",
        machine_name="Finishing Line (Shot Blast & Fettling 90kW)",
        implemented_date="75 days ago",
        predicted_sec_improvement_pct=8.0,
        actual_sec_improvement_pct=8.9,
        kwh_saved_monthly=2840.0,
        inr_saved_monthly=23288.0,
        co2_avoided_kg_monthly=2033.0,
        production_impact_pct=+0.5,
        quality_impact_pct=0.0,
        variance_explanation="Exceeded predicted target by +0.9% due to higher proportion of small automotive bracket castings requiring shorter shot cycles.",
        verification_methodology="IPMVP Option A (Key Parameter Measurement with Continuous Runtime Logging)"
    ))

    return records

def get_action_verification_matrix(action_id: Optional[str] = None) -> List[PredictedVsActualVerification]:
    """
    Generates deterministic Before vs Predicted vs Actual data comparison.
    Explicitly distinguishes between PREDICTED and SIMULATED ACTUAL,
    and qualifies 'VERIFIED PRODUCTION-SAFE SAVING'.
    """
    items = []
    applied = factory_simulator.applied_actions

    # Action 1: Compressor 02 Auto-Idle Shutdown
    # Safe candidate in Scenario A
    is_c2_applied = "action_compressor_unloaded_shutdown" in applied
    stage_c2 = "VERIFIED" if is_c2_applied else "PREDICTED"
    
    # Machine values for Compressor 02
    c2_before_kwh = 336.0
    c2_pred_kwh = 228.0
    c2_actual_kwh = 230.8 if is_c2_applied else 230.8 # simulated actual
    
    c2_rows = [
        MetricComparisonRow(
            metric="Daily Energy",
            unit="kWh/day",
            before=c2_before_kwh,
            predicted=c2_pred_kwh,
            actual=c2_actual_kwh,
            variance_pct=round(((c2_actual_kwh - c2_pred_kwh) / c2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Specific Energy Consumption (SEC)",
            unit="kWh/ton",
            before=round(c2_before_kwh / NOMINAL_DAILY_PRODUCTION_TONS, 2), # 13.71
            predicted=round(c2_pred_kwh / NOMINAL_DAILY_PRODUCTION_TONS, 2), # 9.31
            actual=round(c2_actual_kwh / NOMINAL_DAILY_PRODUCTION_TONS, 2), # 9.42
            variance_pct=round(((c2_actual_kwh - c2_pred_kwh) / c2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Daily Energy Cost",
            unit="INR/day",
            before=round(c2_before_kwh * ELECTRICITY_TARIFF_INR_PER_KWH, 1), # 2755.2
            predicted=round(c2_pred_kwh * ELECTRICITY_TARIFF_INR_PER_KWH, 1), # 1869.6
            actual=round(c2_actual_kwh * ELECTRICITY_TARIFF_INR_PER_KWH, 1), # 1892.6
            variance_pct=round(((c2_actual_kwh - c2_pred_kwh) / c2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Daily Carbon Emissions",
            unit="kg CO2/day",
            before=round(c2_before_kwh * GRID_CO2_FACTOR_KG_PER_KWH, 1), # 240.6
            predicted=round(c2_pred_kwh * GRID_CO2_FACTOR_KG_PER_KWH, 1), # 163.2
            actual=round(c2_actual_kwh * GRID_CO2_FACTOR_KG_PER_KWH, 1), # 165.3
            variance_pct=round(((c2_actual_kwh - c2_pred_kwh) / c2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Production Throughput",
            unit="tons/day",
            before=NOMINAL_DAILY_PRODUCTION_TONS,
            predicted=NOMINAL_DAILY_PRODUCTION_TONS,
            actual=NOMINAL_DAILY_PRODUCTION_TONS,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Casting Quality Pass Rate",
            unit="%",
            before=98.8,
            predicted=98.8,
            actual=98.8,
            variance_pct=0.0
        )
    ]

    actual_kwh_saved_c2 = round(c2_before_kwh - c2_actual_kwh, 1) # 105.2 kWh/day
    pred_kwh_saved_c2 = round(c2_before_kwh - c2_pred_kwh, 1) # 108.0 kWh/day
    pred_err_c2 = round(abs(pred_kwh_saved_c2 - actual_kwh_saved_c2) / pred_kwh_saved_c2 * 100, 2)

    items.append(PredictedVsActualVerification(
        action_id="action_compressor_unloaded_shutdown",
        action_title="90-sec Auto-Idle Shutdown & Tighten Pressure Band to 6.6 bar",
        machine_name="Compressor 02 (Kaeser Screw 75kW)",
        lifecycle_stage="VERIFIED" if is_c2_applied else "PREDICTED",
        verification_status="VERIFIED PRODUCTION-SAFE SAVING" if is_c2_applied else "SIMULATED ACTUAL - PENDING VERIFICATION",
        is_production_safe_saving=True,
        disclaimer="DEMO — SIMULATED POST-ACTION DATA",
        real_deployment_note="In real deployment, verification requires actual sub-meter measurements under IPMVP Option B with baseline normalization.",
        rows=c2_rows,
        prediction_error_pct=pred_err_c2,
        actual_kwh_saved=actual_kwh_saved_c2,
        actual_sec_improvement_pct=round((actual_kwh_saved_c2 / c2_before_kwh) * 100, 1),
        actual_cost_saved_inr=round(actual_kwh_saved_c2 * ELECTRICITY_TARIFF_INR_PER_KWH * 30, 0),
        actual_co2_avoided_kg=round(actual_kwh_saved_c2 * GRID_CO2_FACTOR_KG_PER_KWH * 30, 0),
        production_maintained=True,
        quality_maintained=True,
        machine_limits_maintained=True,
        energy_reduction_positive=True,
        risk_acceptable=True,
        evidence_sufficient=True,
        variance_explanation="Simulated actual post-action run shows 105.2 kWh saved vs 108.0 kWh predicted (2.59% variance) due to dynamic air receiver buffer charging.",
        verification_methodology="IPMVP Option B (Machine Sub-meter Isolation & Pressure Threshold Verification)"
    ))

    # Action 2: Furnace 02 Refractory Patch & Lid Seal
    is_f2_applied = "action_furnace_refractory_patch" in applied
    f2_before_kwh = 624.0
    f2_pred_kwh = 360.0
    f2_actual_kwh = 368.0

    f2_rows = [
        MetricComparisonRow(
            metric="Daily Energy",
            unit="kWh/day",
            before=f2_before_kwh,
            predicted=f2_pred_kwh,
            actual=f2_actual_kwh,
            variance_pct=round(((f2_actual_kwh - f2_pred_kwh) / f2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Specific Energy Consumption (SEC)",
            unit="kWh/ton",
            before=round(f2_before_kwh / NOMINAL_DAILY_PRODUCTION_TONS, 2),
            predicted=round(f2_pred_kwh / NOMINAL_DAILY_PRODUCTION_TONS, 2),
            actual=round(f2_actual_kwh / NOMINAL_DAILY_PRODUCTION_TONS, 2),
            variance_pct=round(((f2_actual_kwh - f2_pred_kwh) / f2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Daily Energy Cost",
            unit="INR/day",
            before=round(f2_before_kwh * ELECTRICITY_TARIFF_INR_PER_KWH, 1),
            predicted=round(f2_pred_kwh * ELECTRICITY_TARIFF_INR_PER_KWH, 1),
            actual=round(f2_actual_kwh * ELECTRICITY_TARIFF_INR_PER_KWH, 1),
            variance_pct=round(((f2_actual_kwh - f2_pred_kwh) / f2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Daily Carbon Emissions",
            unit="kg CO2/day",
            before=round(f2_before_kwh * GRID_CO2_FACTOR_KG_PER_KWH, 1),
            predicted=round(f2_pred_kwh * GRID_CO2_FACTOR_KG_PER_KWH, 1),
            actual=round(f2_actual_kwh * GRID_CO2_FACTOR_KG_PER_KWH, 1),
            variance_pct=round(((f2_actual_kwh - f2_pred_kwh) / f2_pred_kwh) * 100, 2)
        ),
        MetricComparisonRow(
            metric="Production Throughput",
            unit="tons/day",
            before=NOMINAL_DAILY_PRODUCTION_TONS,
            predicted=NOMINAL_DAILY_PRODUCTION_TONS,
            actual=NOMINAL_DAILY_PRODUCTION_TONS,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Casting Quality Pass Rate",
            unit="%",
            before=98.8,
            predicted=98.8,
            actual=98.8,
            variance_pct=0.0
        )
    ]

    actual_kwh_saved_f2 = round(f2_before_kwh - f2_actual_kwh, 1) # 256.0 kWh/day
    pred_kwh_saved_f2 = round(f2_before_kwh - f2_pred_kwh, 1) # 264.0 kWh/day
    pred_err_f2 = round(abs(pred_kwh_saved_f2 - actual_kwh_saved_f2) / pred_kwh_saved_f2 * 100, 2)

    items.append(PredictedVsActualVerification(
        action_id="action_furnace_refractory_patch",
        action_title="Furnace 02 Refractory Patch & Lid Seal",
        machine_name="Furnace 02 (Holding Furnace 450kW)",
        lifecycle_stage="VERIFIED" if is_f2_applied else "PREDICTED",
        verification_status="VERIFIED PRODUCTION-SAFE SAVING" if is_f2_applied else "SIMULATED ACTUAL - PENDING VERIFICATION",
        is_production_safe_saving=True,
        disclaimer="DEMO — SIMULATED POST-ACTION DATA",
        real_deployment_note="In real deployment, verification requires actual sub-meter measurements under IPMVP Option B with baseline normalization.",
        rows=f2_rows,
        prediction_error_pct=pred_err_f2,
        actual_kwh_saved=actual_kwh_saved_f2,
        actual_sec_improvement_pct=round((actual_kwh_saved_f2 / f2_before_kwh) * 100, 1),
        actual_cost_saved_inr=round(actual_kwh_saved_f2 * ELECTRICITY_TARIFF_INR_PER_KWH * 30, 0),
        actual_co2_avoided_kg=round(actual_kwh_saved_f2 * GRID_CO2_FACTOR_KG_PER_KWH * 30, 0),
        production_maintained=True,
        quality_maintained=True,
        machine_limits_maintained=True,
        energy_reduction_positive=True,
        risk_acceptable=True,
        evidence_sufficient=True,
        variance_explanation="Simulated actual post-action run saves 256.0 kWh/day vs 264.0 kWh/day predicted (3.03% variance) reflecting initial patch refractory curing dynamics.",
        verification_methodology="IPMVP Option B (Holding Furnace Sub-meter + Crucible Shell Surface Temperature)"
    ))

    # Action 3: Unsafe candidate for contrast (Compressor 02 Pressure Drop to 5.2 bar)
    # Demonstrates how the constraint gate and verification engine REJECT unsafe actions
    unsafe_rows = [
        MetricComparisonRow(
            metric="Daily Energy",
            unit="kWh/day",
            before=336.0,
            predicted=215.0,
            actual=260.0,
            variance_pct=20.9
        ),
        MetricComparisonRow(
            metric="Specific Energy Consumption (SEC)",
            unit="kWh/ton",
            before=13.71,
            predicted=8.78,
            actual=14.86, # SEC actually WORSENS due to production collapse!
            variance_pct=69.2
        ),
        MetricComparisonRow(
            metric="Daily Energy Cost",
            unit="INR/day",
            before=2755.2,
            predicted=1763.0,
            actual=2132.0,
            variance_pct=20.9
        ),
        MetricComparisonRow(
            metric="Daily Carbon Emissions",
            unit="kg CO2/day",
            before=240.6,
            predicted=154.0,
            actual=186.2,
            variance_pct=20.9
        ),
        MetricComparisonRow(
            metric="Production Throughput",
            unit="tons/day",
            before=24.5,
            predicted=24.5,
            actual=17.5, # Throughput crashed by -28.6% due to mould jam!
            variance_pct=-28.6
        ),
        MetricComparisonRow(
            metric="Casting Quality Pass Rate",
            unit="%",
            before=98.8,
            predicted=98.8,
            actual=86.2, # Scrap rate surged due to low squeeze pressure!
            variance_pct=-12.8
        )
    ]

    items.append(PredictedVsActualVerification(
        action_id="action_compressor_lower_pressure_extreme",
        action_title="Lower Operating Pressure to 5.2 bar (UNSAFE CANDIDATE)",
        machine_name="Compressor 02 (Kaeser Screw 75kW)",
        lifecycle_stage="REJECTED",
        verification_status="REJECTED — CONSTRAINT VIOLATION",
        is_production_safe_saving=False,
        disclaimer="DEMO — SIMULATED POST-ACTION DATA",
        real_deployment_note="In real deployment, verification requires actual sub-meter measurements under IPMVP Option B with baseline normalization.",
        rows=unsafe_rows,
        prediction_error_pct=41.3,
        actual_kwh_saved=76.0,
        actual_sec_improvement_pct=-8.4, # SEC degraded!
        actual_cost_saved_inr=-142000.0, # Massive net loss due to scrap!
        actual_co2_avoided_kg=1630.0,
        production_maintained=False, # VIOLATED
        quality_maintained=False,    # VIOLATED
        machine_limits_maintained=False, # VIOLATED (Pressure 5.2 < 6.0 bar min)
        energy_reduction_positive=True,
        risk_acceptable=False,
        evidence_sufficient=True,
        variance_explanation="REJECTED: Pressure drop to 5.2 bar breached DISA moulding machine 6.0 bar minimum pneumatic constraint, causing mould jamming and scrap increase.",
        verification_methodology="REJECTED — Physical Boundary Check Failed (Pressure Threshold 6.0 bar)"
    ))

    # Also keep legacy ID alias for test backward compatibility
    items.append(PredictedVsActualVerification(
        action_id="action_compressor_reduce_pressure",
        action_title="Lower Operating Pressure to 5.2 bar (UNSAFE CANDIDATE)",
        machine_name="Compressor 02 (Kaeser Screw 75kW)",
        lifecycle_stage="REJECTED",
        verification_status="REJECTED — CONSTRAINT VIOLATION",
        is_production_safe_saving=False,
        disclaimer="DEMO — SIMULATED POST-ACTION DATA",
        real_deployment_note="In real deployment, verification requires actual sub-meter measurements under IPMVP Option B with baseline normalization.",
        rows=unsafe_rows,
        prediction_error_pct=41.3,
        actual_kwh_saved=76.0,
        actual_sec_improvement_pct=-8.4,
        actual_cost_saved_inr=-142000.0,
        actual_co2_avoided_kg=1630.0,
        production_maintained=False,
        quality_maintained=False,
        machine_limits_maintained=False,
        energy_reduction_positive=True,
        risk_acceptable=False,
        evidence_sufficient=True,
        variance_explanation="REJECTED: Pressure drop to 5.2 bar breached DISA moulding machine 6.0 bar minimum pneumatic constraint, causing mould jamming and scrap increase.",
        verification_methodology="REJECTED — Physical Boundary Check Failed (Pressure Threshold 6.0 bar)"
    ))

    # Action 4: TOD Scheduling
    is_tod_applied = "action_tod_rescheduling" in applied
    tod_rows = [
        MetricComparisonRow(
            metric="Daily Energy",
            unit="kWh/day",
            before=14350.0,
            predicted=14350.0,
            actual=14350.0,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Blended Tariff Rate",
            unit="₹/kWh",
            before=8.20,
            predicted=6.85,
            actual=6.85,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Daily Energy Cost",
            unit="INR/day",
            before=117670.0,
            predicted=98298.0,
            actual=98298.0,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Daily Carbon Emissions",
            unit="kg CO2/day",
            before=10275.0,
            predicted=10275.0,
            actual=10275.0,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Production Throughput",
            unit="tons/day",
            before=24.5,
            predicted=24.5,
            actual=24.5,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Casting Quality Pass Rate",
            unit="%",
            before=98.8,
            predicted=98.8,
            actual=98.8,
            variance_pct=0.0
        )
    ]

    items.append(PredictedVsActualVerification(
        action_id="action_tod_rescheduling",
        action_title="Shift Primary Heat Pre-Melting to Night Off-Peak Slot (03:00 - 06:00)",
        machine_name="Furnace 01 & 02 Melt System",
        lifecycle_stage="VERIFIED" if is_tod_applied else "PREDICTED",
        verification_status="VERIFIED PRODUCTION-SAFE SAVING" if is_tod_applied else "SIMULATED ACTUAL - PENDING VERIFICATION",
        is_production_safe_saving=True,
        disclaimer="DEMO — SIMULATED POST-ACTION DATA",
        real_deployment_note="In real deployment, verification requires actual utility TOD smart meter revenue interval logs.",
        rows=tod_rows,
        prediction_error_pct=0.0,
        actual_kwh_saved=0.0,
        actual_sec_improvement_pct=0.0,
        actual_cost_saved_inr=126000.0,
        actual_co2_avoided_kg=0.0,
        production_maintained=True,
        quality_maintained=True,
        machine_limits_maintained=True,
        energy_reduction_positive=True,
        risk_acceptable=True,
        evidence_sufficient=True,
        variance_explanation="Tariff savings verified against utility 15-minute TOD interval tariff structure with zero net change in net kWh or pouring times.",
        verification_methodology="IPMVP Option C (Utility Revenue Billing Meter Interval Analysis)"
    ))

    # Action 5: Missing Sensor Withheld Action
    missing_sensor_rows = [
        MetricComparisonRow(
            metric="Daily Energy",
            unit="kWh/day",
            before=336.0,
            predicted=0.0,
            actual=336.0,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Vibration Acceleration",
            unit="mm/s² RMS",
            before=0.0,
            predicted=0.0,
            actual=0.0,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Daily Energy Cost",
            unit="INR/day",
            before=2755.2,
            predicted=0.0,
            actual=2755.2,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Daily Carbon Emissions",
            unit="kg CO2/day",
            before=240.6,
            predicted=0.0,
            actual=240.6,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Production Throughput",
            unit="tons/day",
            before=24.5,
            predicted=24.5,
            actual=24.5,
            variance_pct=0.0
        ),
        MetricComparisonRow(
            metric="Casting Quality Pass Rate",
            unit="%",
            before=98.8,
            predicted=98.8,
            actual=98.8,
            variance_pct=0.0
        )
    ]

    items.append(PredictedVsActualVerification(
        action_id="action_compressor_bearing_overhaul_unsupported",
        action_title="Compressor Bearing Overhaul (WITHHELD — MISSING SENSOR)",
        machine_name="Compressor 02 (Kaeser Screw 75kW)",
        lifecycle_stage="WITHHELD",
        verification_status="WITHHELD — INSUFFICIENT SENSOR EVIDENCE",
        is_production_safe_saving=False,
        disclaimer="DEMO — SIMULATED POST-ACTION DATA",
        real_deployment_note="In real deployment, verification requires actual sub-meter and vibration telemetry after sensor installation.",
        rows=missing_sensor_rows,
        prediction_error_pct=0.0,
        actual_kwh_saved=0.0,
        actual_sec_improvement_pct=0.0,
        actual_cost_saved_inr=0.0,
        actual_co2_avoided_kg=0.0,
        production_maintained=True,
        quality_maintained=True,
        machine_limits_maintained=True,
        energy_reduction_positive=False,
        risk_acceptable=False,
        evidence_sufficient=False,
        variance_explanation="Trust Protocol Withholding: Vibration sensor is not installed on Compressor 02 bearing housing. Diagnosis and intervention withheld to prevent ungrounded mechanical overhaul or false claims.",
        verification_methodology="WITHHELD (Sensor Evidence Gating - Requires Accelerometer Deployment)"
    ))

    if action_id:
        filtered = [x for x in items if x.action_id == action_id]
        return filtered if filtered else items
    return items

def verify_single_action(action_id: str) -> Dict[str, Any]:
    """
    Evaluates whether an action qualifies as a VERIFIED PRODUCTION-SAFE SAVING.
    Enforces all 5 golden criteria:
    1. Positive energy savings confirmed in post-action state
    2. Production throughput maintained >= 100%
    3. Product quality tolerance maintained
    4. Machine operating physical limits respected
    5. Required sensory evidence sufficient
    """
    matrix = get_action_verification_matrix(action_id)
    matched = next((m for m in matrix if m.action_id == action_id), None)
    
    if not matched:
        return {
            "success": False,
            "error": f"Action ID '{action_id}' not found in verification registry."
        }

    is_verified = (
        matched.energy_reduction_positive and
        matched.production_maintained and
        matched.quality_maintained and
        matched.machine_limits_maintained and
        matched.risk_acceptable and
        matched.evidence_sufficient
    )

    return {
        "action_id": matched.action_id,
        "action_title": matched.action_title,
        "machine_name": matched.machine_name,
        "is_verified": is_verified,
        "verification_verdict": "VERIFIED PRODUCTION-SAFE SAVING" if is_verified else "REJECTED - NOT PRODUCTION-SAFE",
        "criteria_audit": {
            "energy_reduction_positive": matched.energy_reduction_positive,
            "production_throughput_maintained": matched.production_maintained,
            "quality_tolerance_maintained": matched.quality_maintained,
            "machine_operating_limits_passed": matched.machine_limits_maintained,
            "sensory_evidence_sufficient": matched.evidence_sufficient
        },
        "post_action_savings": {
            "kwh_saved_daily": matched.actual_kwh_saved,
            "sec_improvement_pct": matched.actual_sec_improvement_pct,
            "cost_saved_monthly_inr": matched.actual_cost_saved_inr,
            "co2_avoided_monthly_kg": matched.actual_co2_avoided_kg
        },
        "variance_analysis": matched.variance_explanation,
        "disclaimer": "DEMO — SIMULATED POST-ACTION DATA. Not real factory measurements."
    }
